import os
import json
from datetime import datetime
from typing import List, Dict
import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY

class ExportSystem:
    """Export stories to various eBook formats"""
    
    def __init__(self):
        self.output_dir = "exports"
        os.makedirs(self.output_dir, exist_ok=True)
    
    def export_to_epub(self, story_data: dict, author: str) -> str:
        """Export to ePub format (basic HTML-based)"""
        title = story_data['title']
        chapters = story_data.get('chapters', [])
        content = story_data.get('content', '')
        
        # Create basic ePub structure
        # Note: Full ePub requires ebooklib library, this is simplified
        
        html_content = self._generate_html_book(title, author, chapters if chapters else [{'title': 'Story', 'content': content}])
        
        filename = f"{self.output_dir}/{title[:30].replace(' ', '_')}.epub"
        
        # For now, save as HTML (in production, use ebooklib to create proper ePub)
        with open(filename.replace('.epub', '.html'), 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filename
    
    def export_to_mobi(self, story_data: dict, author: str) -> str:
        """Export to MOBI format
        Note: MOBI requires Amazon's KindleGen or Calibre for conversion
        This creates the intermediate HTML that can be converted
        """
        # Same as ePub for now - would need KindleGen for actual MOBI
        return self.export_to_epub(story_data, author).replace('.epub', '.mobi')
    
    def export_to_pdf_kdp(self, story_data: dict, author: str, cover_path: str = None) -> str:
        """Export to KDP-ready PDF (6x9 format)"""
        title = story_data['title']
        chapters = story_data.get('chapters', [])
        content = story_data.get('content', '')
        
        filename = f"{self.output_dir}/{title[:30].replace(' ', '_')}_KDP.pdf"
        
        # Create PDF (6x9 inches - standard novel size)
        page_size = (6 * inch, 9 * inch)
        doc = SimpleDocTemplate(
            filename,
            pagesize=page_size,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            leftMargin=0.5 * inch,
            rightMargin=0.5 * inch
        )
        
        # Styles
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor='black',
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        author_style = ParagraphStyle(
            'CustomAuthor',
            parent=styles['Normal'],
            fontSize=14,
            textColor='gray',
            spaceAfter=50,
            alignment=TA_CENTER,
            fontName='Helvetica'
        )
        
        chapter_style = ParagraphStyle(
            'CustomChapter',
            parent=styles['Heading2'],
            fontSize=16,
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
            alignment=TA_JUSTIFY,
            fontName='Times-Roman'
        )
        
        # Build PDF content
        story_elements = []
        
        # Title page
        story_elements.append(Spacer(1, 2 * inch))
        story_elements.append(Paragraph(title, title_style))
        story_elements.append(Paragraph(f"by {author}", author_style))
        story_elements.append(PageBreak())
        
        # Copyright page
        copyright_text = f"""<para align=center>
        Copyright © {datetime.now().year} by {author}<br/>
        All rights reserved.<br/>
        <br/>
        Generated by GhostWriter AI
        </para>"""
        story_elements.append(Spacer(1, 2 * inch))
        story_elements.append(Paragraph(copyright_text, styles['Normal']))
        story_elements.append(PageBreak())
        
        # Chapters
        if chapters:
            for chapter in chapters:
                story_elements.append(Paragraph(chapter['title'], chapter_style))
                story_elements.append(Spacer(1, 0.3 * inch))
                
                # Split content into paragraphs
                paragraphs = chapter['content'].split('\n')
                for para in paragraphs:
                    if para.strip():
                        story_elements.append(Paragraph(para.strip(), body_style))
                        story_elements.append(Spacer(1, 0.15 * inch))
                
                story_elements.append(PageBreak())
        else:
            # Single content block
            paragraphs = content.split('\n')
            for para in paragraphs:
                if para.strip():
                    story_elements.append(Paragraph(para.strip(), body_style))
                    story_elements.append(Spacer(1, 0.15 * inch))
        
        # Build PDF
        doc.build(story_elements)
        
        return filename
    
    def export_to_print_pdf(self, story_data: dict, author: str, cover_path: str) -> str:
        """Export to print-ready PDF with cover"""
        # Similar to KDP but includes cover
        kdp_file = self.export_to_pdf_kdp(story_data, author)
        # In production, would merge cover PDF with content PDF
        return kdp_file.replace('_KDP', '_PRINT')
    
    def _generate_html_book(self, title: str, author: str, chapters: List[Dict]) -> str:
        """Generate HTML book format"""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: Georgia, serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            line-height: 1.8;
        }}
        h1 {{
            text-align: center;
            font-size: 2.5em;
            margin-bottom: 0.5em;
        }}
        .author {{
            text-align: center;
            font-size: 1.2em;
            color: #666;
            margin-bottom: 3em;
        }}
        h2 {{
            text-align: center;
            font-size: 1.8em;
            margin-top: 3em;
            margin-bottom: 1.5em;
            page-break-before: always;
        }}
        p {{
            text-align: justify;
            margin-bottom: 1em;
            text-indent: 2em;
        }}
        .chapter {{
            page-break-before: always;
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p class="author">by {author}</p>
"""
        
        for chapter in chapters:
            html += f"""    <div class="chapter">
        <h2>{chapter['title']}</h2>
"""
            paragraphs = chapter['content'].split('\n')
            for para in paragraphs:
                if para.strip():
                    html += f"        <p>{para.strip()}</p>\n"
            
            html += "    </div>\n"
        
        html += """</body>
</html>"""
        
        return html
    
    def generate_blurb(self, story_data: dict, max_words: int = 250) -> str:
        """Generate marketing blurb/description for the book"""
        from llm_client import llm, GHOSTWRITER_FICTION
        from config import settings
        
        title = story_data['title']
        premise = story_data.get('metadata', {}).get('premise', '')
        
        prompt = f"""Write a compelling book blurb (back cover description) for:

Title: {title}
Premise: {premise}

Max {max_words} words. Make it enticing, mysterious, and hook the reader. End with a cliffhanger question or statement."""
        
        blurb = llm.generate(prompt, GHOSTWRITER_FICTION, settings.creative_model)
        return blurb.strip()
    
    def generate_author_bio(self, author_name: str, style: str = "mysterious") -> str:
        """Generate author bio"""
        from llm_client import llm, GHOSTWRITER_FICTION
        from config import settings
        
        prompt = f"""Write a {style} author bio for: {author_name}

Max 150 words. Make it intriguing and match the tone of dark fiction/mystery writing. Add a touch of humor."""
        
        bio = llm.generate(prompt, GHOSTWRITER_FICTION, settings.creative_model)
        return bio.strip()


export_system = ExportSystem()
